angular.module('weatherApp', []);

/*
Okay, so, let's define the functionality of this app...
User goes to the input and types a city, then clicks the Submit button...
The City Information panel populates with the name of city, Lat/Long, Temperature, Pressure, Humidity, Lowest Temp, Highest Temp, Wind Speed...
The Search History panel populates with the search results and the exact date and time that each search was made.
 */